{% set name = "requests_ntlm" %}
{% set version = "1.3.0" %}
{% set sha256 = "b29cc2462623dffdf9b88c43e180ccb735b4007228a542220e882c58ae56c668" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pyspnego >=0.1.6
    - requests >=2.0.0
    - cryptography >=1.3

test:
  imports:
    - requests_ntlm
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/requests/requests-ntlm
  license: ISC
  license_file: LICENSE
  summary: NTLM authentication support for Requests.

  description: |
    This package allows for HTTP NTLM authentication using the requests library.
  dev_url: https://github.com/requests/requests-ntlm

extra:
  recipe-maintainers:
    - synapticarbors
